### PR TITLE
Default tagsAsFields

### LINKED ISSUE #4: Discuss whether to not move some fields to be int
This was previously discussed when field types were added, but we didn't change them as it would [break](https://github.com/grafana/k6/pull/1395#issuecomment-672587974) if used on an influxdb with the same fields but different types. 

Even then I was of the opinion that this might not be so bad given the benefit of all future deployments having more accurate field types, so I guess now is a good time to probably do that?

We might also want to revisit the tag to fields list and see if we should not add some newer tag

### PR DESCRIPTION
**Pull request by codebien**
Closes #4

### CODE REVIEW

**Comment by codebien** [comment]
@MStoykov In this way, I expect a less stressed system during `k6` run (e.g. in the basic case `K6_INFLUXDB_ORG .... ./k6+influxdb run --out=http://localhost:8086 script.js`). Less indexed fields to maintain for InfluxDB during the writing stage. If the user hits some performance issues during queries or needs to query heavily some not indexed field then s/he can still change the configuration.
Let me know if you think some other fields are heavily used in common cases.

**Comment by MStoykov** [comment]
I don't think that everything needs to be a field. Arguably `name` should probably be an index so it can be used for better queries. 
I would also say that `method` and `status` also will likely be used for queries all the time. 

Looking at the list of tags here, I am not particularly certain there are any we should ... add to the list as most of those have a very *small* set of values or will be very important to make queries on like `name`

**Comment by codebien** [comment]
> I would also say that method and status also will likely be used for queries all the time.

They are already excluded from the list so they would be indexed.

>Looking at the list of tags here, I am not particularly certain there are any we should
So would you prefer to have just `"vu:int", "iter:int", "url"`?

**Comment by codebien** [comment]
@MStoykov updated the PR with the original proposal from the issue description

**Review by MStoykov — APPROVED** [review]

**Pull request merged**
